=== mbizhani/Thallo/thallo-itest/src/main/resources/thallo-itest.dtd
<!ELEMENT itest (kafka|redis|services|params|rests)*>
	<!ELEMENT kafka (#PCDATA)>
	<!ELEMENT redis (#PCDATA)>
	<!ELEMENT services (bootApp|remote)*>
	<!ELEMENT bootApp (#PCDATA)>
	<!ATTLIST bootApp
		name CDATA #REQUIRED
		fqn CDATA #REQUIRED
		profile CDATA #IMPLIED
		context CDATA #IMPLIED>
	<!ELEMENT remote (#PCDATA)>
	<!ATTLIST remote
		name CDATA #REQUIRED
		host CDATA #REQUIRED
		port CDATA #REQUIRED
		context CDATA #IMPLIED>
	<!ELEMENT params (param)*>
	<!ELEMENT param (#PCDATA)>
	<!ATTLIST param
		name CDATA #REQUIRED
		value CDATA #REQUIRED>
	<!ELEMENT rests (rest)*>
	<!ELEMENT rest (request|response)*>
	<!ATTLIST rest
		service CDATA #IMPLIED
		bearerToken CDATA #IMPLIED
		method (GET|POST|PUT|DELETE) #REQUIRED
		uri CDATA #IMPLIED
		url CDATA #IMPLIED>
	<!ELEMENT request (body|response)*>
	<!ELEMENT body (#PCDATA)>
	<!ELEMENT response (assert)*>
	<!ATTLIST response
		ignoreOthers (true|false) #IMPLIED
		status (OK|CREATED|BAD_REQUEST|UNAUTHORIZED|FORBIDDEN|NOT_FOUND|METHOD_NOT_ALLOWED|NOT_ACCEPTABLE) #REQUIRED>
	<!ELEMENT assert (#PCDATA)>
	<!ATTLIST assert
		hasValue (true|false) #IMPLIED
		path CDATA #REQUIRED
		storeAsParam CDATA #IMPLIED
		type (STRING|INTEGER|REAL|BOOLEAN|LIST) #REQUIRED
		value CDATA #IMPLIED>

=== mbizhani/Thallo/thallo-itest/src/test/resources/itest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE itest PUBLIC
	"Devocative/Thallo ITest"
	"http://www.devocative.org/dtd/thallo-itest.dtd">

<itest>
	<kafka/>
	<redis/>

	<services>
		<!--<bootApp name="Kernel" fqn="ir.maxsa.kernel.KernelApplication" profile="h2" context="/kernel"/>-->
		<remote name="Kernel" host="localhost" port="8080" context="/kernel"/>
	</services>

	<params>
		<param name="idx" value="011"/>

		<param name="ShopName" value="shop${idx}"/>
		<param name="MUsername" value="+989121234${idx}"/>
		<param name="MPassword" value="asd"/>
		<param name="ShopDomain" value="myshop.com"/>
		<param name="ShopUrl" value="${ShopDomain}:${Kernel.port}${Kernel.context}"/>

		<param name="CUsername" value="+989219876${idx}"/>
		<param name="CPassword" value="qaz"/>
	</params>

	<rests>

		<!-- MERCHANT-->

		<rest service="Kernel" uri="/api/auth/registrations" method="POST">
			<request>
				<body><![CDATA[
{
	"storeName": "${ShopName}",
	"username": "${MUsername}",
	"password": "${MPassword}"
}
]]></body>
				<response status="OK">
					<assert path="personId" type="STRING" storeAsParam="PersonID"/>
					<assert path="usernameType" type="STRING" value="Cell"/>
				</response>

			</request>
		</rest>

		<rest service="Kernel" uri="/api/auth/registrations/${PersonID}/1234" method="GET">
			<response status="OK">
				<assert path="access_token" type="STRING" storeAsParam="MerchantToken"/>
				<assert path="token_type" type="STRING" value="bearer"/>
			</response>
		</rest>

		<rest service="Kernel" uri="/api/stores/current" method="GET" bearerToken="${MerchantToken}">
			<response status="OK">
				<assert path="id" type="STRING" storeAsParam="StoreID"/>
				<assert path="version" type="INTEGER" value="0" storeAsParam="StoreVer"/>
			</response>
		</rest>

		<rest service="Kernel" uri="/api/stores/current" method="PUT" bearerToken="${MerchantToken}">
			<request>
				<body><![CDATA[
{
	"name": "myshop",
	"version": ${StoreVer},
	"domainName": "localhost"
}
]]></body>
				<response status="BAD_REQUEST">
					<assert path="errors" type="LIST"/>
				</response>
			</request>

			<request>
				<body><![CDATA[
{
	"name": "myshop",
	"title": {"en": "MyShop"},
	"version": ${StoreVer},
	"domainName": "myshop.com"
}
]]></body>
				<response status="OK" ignoreOthers="true">
					<assert path="version" type="INTEGER" storeAsParam="StoreVer"/>
				</response>
			</request>
		</rest>


		<!-- CUSTOMER -->

		<rest url="${ShopUrl}/api/customers/registrations/anonymous" method="GET">
			<response status="OK">
				<assert path="access_token" type="STRING" storeAsParam="GuestToken"/>
				<assert path="token_type" type="STRING" value="bearer"/>
			</response>
		</rest>

		<rest url="${ShopUrl}/api/customers/registrations" method="POST" bearerToken="${GuestToken}">
			<request>
				<body><![CDATA[
{
	"cell": "${CUsername}",
	"password": "${CPassword}",
	"firstName": "A1",
	"lastName": "A2",
	"address": {
		"address": "address",
		"postalCode": "1234567890",
		"cityId": 1000
	}
}
]]></body>
				<response status="OK">
					<assert path="customerId" type="STRING" storeAsParam="CustomerID"/>
					<assert path="usernameType" type="STRING" value="Cell"/>
				</response>

			</request>
		</rest>

		<rest url="${ShopUrl}/api/customers/registrations/${CustomerID}/1234" method="GET" bearerToken="${GuestToken}">
			<response status="OK">
				<assert path="access_token" type="STRING" storeAsParam="CustomerToken"/>
				<assert path="token_type" type="STRING" value="bearer"/>
			</response>
		</rest>

		<rest url="${ShopUrl}/api/customers/current/addresses" method="POST" bearerToken="${CustomerToken}">
			<request>
				<body><![CDATA[
{
	"cityId": 2000,
	"address": "address1",
	"postalCode": "1111111111",
	"version": 0
}]]></body>
				<response status="OK"/>
			</request>
		</rest>

		<rest url="${ShopUrl}/api/customers/current" method="GET" bearerToken="${CustomerToken}">
			<response status="OK">
				<assert path="anonymous" type="BOOLEAN" value="false"/>
			</response>
		</rest>

		<rest url="${ShopUrl}/api/customers/current" method="GET" bearerToken="${CustomerToken}">
			<response status="OK">
				<assert path="anonymous" type="BOOLEAN" value="false"/>
			</response>
		</rest>

		<!-- MERCHANT-->

		<rest service="Kernel" uri="/api/customers/search" method="POST" bearerToken="${MerchantToken}">
			<request>
				<body><![CDATA[
{
	"startIndex": 0,
	"count": 10
}
]]></body>
				<response status="OK">
					<assert path="totalCount" type="INTEGER" hasValue="true"/>
				</response>
			</request>
		</rest>

	</rests>
</itest>
